---
title: "final_report"
author: "Elaine Fan"
date: "2025-11-04"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
df <- read.csv("TextMessages.csv")
```

```{r}
library(tidyverse)
df_long <- df %>% pivot_longer(cols = c(Baseline, Six_months), names_to = "Time", values_to = "Text_Count")

```

```{r}
library(ggplot2)
ggplot(df_long, aes(x = Time, y = Text_Count, fill = Time)) + geom_boxplot() + facet_wrap(~Group) +
  labs(title = "Text Messages by Group and Time", x = "Time Point", y = "Number of Text Messages",
       fill = "Group") 
```

Code from Josh's .R file

```{r}
library(tidyverse)

df <- readr::read_csv("TextMessages.csv")

# reshape data to combine our time (baseline and 6 months) into one column

df_combine <- df %>% 
  pivot_longer(
    cols = c(Baseline, Six_months),
    names_to = "Time",
    values_to = "Messages"
  )

# create our facted bar plot

ggplot(df_combine, aes(x = Time, y = Messages, fill = Time)) +
  geom_col() +
  facet_wrap(~ Group) +
  labs(
    title = "Text messages by Group and Time",
    x = "Time",
    y = "# of Text messages",
    fill = "Time"
  ) +
  theme_minimal()
```
```{r}
library(tidyverse)

readr::read_csv("TextMessages.csv")

# reshape data to combine our time (baseline and 6 months) into one column

df_combine <- df %>% 
  pivot_longer(
    cols = c(Baseline, Six_months),
    names_to = "Time",
    values_to = "Messages"
  )

# output our summary statistics

summary_stats <- df_combine %>% 
  group_by(Group, Time) %>% 
  summarise(
    mean = mean(Messages),
    sd = sd(Messages),
    n = n(),
    var = var(Messages),
    min = min(Messages),
    max = max(Messages),
    IQR = IQR(Messages),
    median = median(Messages),
    .groups = "drop"
  )

# place summary stats in a table

knitr::kable(summary_stats, digits = 2,
             caption = "Summary Statistics for Messages by Group and Time")
```
